spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=SEAL;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG