package com.sealhackathon.notification.domain.enums;

public enum NotificationType {

    ACCOUNT_APPROVED,
    ACCOUNT_REJECTED,
    INTERNAL_ACCOUNT_CREATED,
    TEAM_REGISTERED,
    TEAM_CONFIRMED,
    INVITATION_RECEIVED,
    MENTOR_TEAM_ASSIGNED,
    SUBMISSION_CREATED,
    JUDGE_ASSIGNED,
    MENTOR_ASSIGNED,
    SCORING_REOPENED,
    RESULTS_PUBLISHED,
    DISPUTE_FILED,
    JOIN_REQUEST_RECEIVED,
    JOIN_REQUEST_ACCEPTED,
    JOIN_REQUEST_REJECTED,
    LEAVE_REQUEST_CREATED,
    LEAVE_REQUEST_APPROVED,
    LEAVE_REQUEST_REJECTED,
    INVITATION_ACCEPTED,
    MEMBER_KICKED
}
