package com.sealhackathon.notification.domain.enums;

public enum NotificationType {

    ACCOUNT_APPROVED,
    ACCOUNT_REJECTED,
    INTERNAL_ACCOUNT_CREATED,
    TEAM_REGISTERED,
    TEAM_CONFIRMED,
    INVITATION_RECEIVED,
    MENTOR_TEAM_ASSIGNED,
    SUBMISSION_CREATED,
    JUDGE_ASSIGNED,
    MENTOR_ASSIGNED,
    SCORING_REOPENED,
    RESULTS_PUBLISHED,
    DISPUTE_FILED
}
