app.frontend.url=http://localhost:3000
app.cors.allowed-origins=http://localhost:3000
app.jwt.issuer=seal-hackathon-dev
app.storage.upload-dir=./uploads
app.seeder.default-password=12345678
app.seeder.student-id-prefix=SE19100
app.protected-emails=admin@seal.com,coordinator@seal.com,lecturer1@fpt.edu.vn,lecturer2@fpt.edu.vn,lecturer3@fpt.edu.vn,lecturer4@fpt.edu.vn,lecturer5@fpt.edu.vn
