spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=SEAL;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345

  jpa:
    hibernate:
      ddl-auto: none  # RẤT QUAN TRỌNG: Để Flyway làm việc, đừng để hibernate tự sửa bảng
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  flyway:
    enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

# KHỐI CẤU HÌNH JWT PHẢI ĐẶT SÁT LỀ TRÁI NHƯ THẾ NÀY:
application:
  security:
    jwt:
      # Chuỗi secret key này phải dài ít nhất 256-bit (32 ký tự). Hãy giữ bí mật chuỗi này!
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      # Thời gian sống của Access Token (Ví dụ: 1 ngày = 86400000 ms)
      expiration: 86400000
      refresh-token:
        # Thời gian sống của Refresh Token (Ví dụ: 7 ngày = 604800000 ms)
        expiration: 604800000